##################################################
# Snippet
##################################################

# Snippet 補完
[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['honza/vim-snippets', 'Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert = 1
filetypes = 'snippet'
unite_sources = [ 'neosnippet', 'neosnippet/user', 'neosnippet/runtime']

##################################################
# Visual Model
##################################################

# Visual mode補助
[[plugins]]
repository = 'kana/vim-niceblock'
mappings = '<Plug>'

##################################################
# LANG : php
##################################################

# php ネームスペース
[[plugins]]
repository = 'arnaud-lb/vim-php-namespace'
filetypes = ['php']

[[plugins]]
repository = 'shawncplus/phpcomplete.vim'
filetypes = ['php']

[[plugins]]
repository = 'drwX/php-doc.vim'
filetypes = ['php']

[[plugins]]
repository = 'tobyS/pdv'
filetypes = ['php']

[[plugins]]
repository = 'vim-php/vim-php-refactoring'
filetypes = ['php']

[[plugins]]
repository = 'stephpy/vim-php-cs-fixer'
filetypes = ['php']

##################################################
# lANG : ruby
##################################################

# rsense
[[plugins]]
#repository = 'taichouchou2/vim-rsense'
repository = 'supermomonga/neocomplete-rsense.vim'
filetypes = ['ruby']

# rails.vim (railsのシンタックス、MVCの移動、railsコマンドの利用)
[[plugins]]
repository = 'tpope/vim-rails'
filetypes = ['ruby']

# ruby の do に対する end を補完
[[plugins]]
repository = 'tpope/vim-endwise'
filetypes = ['ruby']

# ruby で def end などのマッチングを行う
[[plugins]]
repository = 'vim-scripts/ruby-matchit'
filetypes = ['ruby']


##################################################
# lANG : javascript
##################################################

# javascript libs syntax
#[[plugins]]
#repository = 'othree/javascript-libraries-syntax.vim'
#filetypes = ['javascript']

# javascript indent
#[[plugins]]
#repository = 'vim-scripts/JavaScript-Indent'
#filetypes = ['javascript']
 
# node.js
[[plugins]]
repository = 'moll/vim-node'
filetypes = ['javascript']

# jsdoc
[[plugins]]
repository = 'heavenshell/vim-jsdoc'
filetypes = ['javascript']

##################################################
# lANG : markdown
##################################################

[[plugins]]
repository = 'shime/vim-livedown'
filetypes = ['markdown']


