##################################################
# 
##################################################

# 非同期タスク実行 (unite等で利用)
[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

# タグ生成
[[plugins]]
repository = 'szw/vim-tags'

# 非同期タスク実行(vim-tags の非同期実行に使用)
[[plugins]]
repository = 'tpope/vim-dispatch'

# webapi.vim (各種web apiをvimから利用)
[[plugins]]
repository = 'mattn/webapi-vim'

# surround.vim (テキストオブジェクトを使いやすく)
[[plugins]]
repository = 'tpope/vim-surround'

# 直感的に選択テキストを移動
[[plugins]]
repository = 't9md/vim-textmanip'

# 直感的にテキスト置換
[[plugins]]
repository = 'osyo-manga/vim-over'

# smartword (全角文字の単語認識)
[[plugins]]
repository = 'kana/vim-smartword'

# vim-quickhl (選択箇所の複数ハイライト)
[[plugins]]
repository = 't9md/vim-quickhl'

# コメントアウト
[[plugins]]
repository = 'tpope/vim-commentary'

# emmet (zencodingの利用)
[[plugins]]
repository = 'mattn/emmet-vim/'

# Autoクローズ系
#[[plugins]]
#repository = 'vim-scripts/AutoClose'

# 括弧のオートクローズ
[[plugins]]
repository = "kana/vim-smartinput"

# end系のオートクローズ
[[plugins]]
repository = "cohama/vim-smartinput-endwise"

# ag (silver seacher による grep)
[[plugins]]
repository = 'rking/ag.vim'

# editorconfig
[[plugins]]
repository = 'editorconfig/editorconfig-vim'

# タブ等による均等整形
[[plugins]]
repository = 'junegunn/vim-easy-align'

##################################################
# UI
##################################################

# 軽量のpowerline系プラグイン
[[plugins]]
repository = 'bling/vim-airline'

# minimap
[[plugins]]
repository = 'severin-lemaignan/vim-minimap'

# color table
[[plugins]]
repository = 'guns/xterm-color-table.vim'

# バイナリエディタ
[[plugins]]
repository = 'Shougo/vinarise.vim'

# 統合インターフェース (unite)
[[plugins]]
repository = 'Shougo/unite.vim'

# ファジーファインダ
[[plugins]]
repository = 'kien/ctrlp.vim'

# ドキュメント参照
[[plugins]]
repository = 'thinca/vim-ref'

# スクリプト実行
[[plugins]]
repository = 'thinca/vim-quickrun'

# vimscript 向け console
[[plugins]]
repository = 'rbtnn/vimconsole.vim'

# ブラウザ・オープン
[[plugins]]
repository = 'tyru/open-browser.vim'

# font size変更
[[plugins]]
repository = 'thinca/vim-fontzoom'

# scrooloose/syntastic.vim (各種ファイルタイプのシンタックスエラーの検出・表示)
[[plugins]]
repository = 'scrooloose/syntastic'

# Tagbar (ctagを見やすく表示) javascriptで利用時にnodeがhung
[[plugins]]
repository = 'majutsushi/tagbar'
repository = 'vim-scripts/tagbar-phpctags'

# Source explorer
[[plugins]]
repository = 'wesleyche/SrcExpl'

# vcscommand.vim (svnの利用)
[[plugins]]
repository = 'harleypig/vcscommand.vim'

# vim-fugitive (git コマンド利用)
[[plugins]]
repository = 'tpope/vim-fugitive'

# git log view (tig相当 fugitive依存) 
[[plugins]]
repository = 'gregsexton/gitv'

# vcsのステータス表示
[[plugins]]
repository = 'mhinz/vim-signify'

# vimplenote.vim (simplenoteの利用)
#[[plugins]]
#repository = 'mattn/vimplenote-vim'

# dir単位のdiff
[[plugins]]
repository = 'vim-scripts/DirDiff.vim'

# インデント見やすく
[[plugins]]
repository = 'Yggdroot/indentLine'

# ファイラUI
[[plugins]]
repository = 'Shougo/vimfiler'

# シェルUI
[[plugins]]
repository = 'Shougo/vimshell.vim'

# シェルUI拡張
[[plugins]]
repository = 'supermomonga/vimshell-pure.vim'

# vimshell と vimfiler でsshを利用するための拡張
[[plugins]]
repository = 'Shougo/neossh.vim'


##################################################
# Unite Source
##################################################

# 最近使用したファイル
[[plugins]]
repository = 'Shougo/neomru.vim'

# unite-outline (Unite:アウトラインソース)
[[plugins]]
repository = 'Shougo/unite-outline'
unite_sources = ['outline']

# unite-locate
[[plugins]]
repository = 'ujihisa/unite-locate'
unite_sources = ['locate']

# unite-spotlight
[[plugins]]
repository = 'choplin/unite-spotlight'
unite_sources = ['spotlight']

# unite-help (Unite:ヘルプソース)
[[plugins]]
repository = 'tsukkee/unite-help'
unite_sources = ['help']

# unite-tag (Unite:ctagソース)
[[plugins]]
repository = 'tsukkee/unite-tag'
unite_sources = ['tag']

# Unite todo source
[[plugins]]
repository = 'kannokanno/unite-todo'
unite_sources = 'todo'

# Unite color scheme source
[[plugins]]
repository = 'ujihisa/unite-colorscheme'
unite_sources = 'colorscheme'

# Unite vcs
[[plugins]]
repository = 'hrsh7th/vim-versions'

# unite-variable 追加
[[plugins]]
repository = 'thinca/vim-editvar'


##################################################
# Syntax
##################################################

# コンテキストによってファイルタイプを検出
[[plugins]]
repository = 'Shougo/context_filetype.vim'

# コンテキストによってfiletypeを自動で変更 
[[plugins]]
repository = 'osyo-manga/vim-precious'

# toml syntax
[[plugins]]
repository = 'cespare/vim-toml'

# json filetype
[[plugins]]
repository = 'elzr/vim-json'

# json 整形
[[plugins]]
repository = '5t111111/neat-json.vim'

# html5.vim (html5シンタックス)
[[plugins]]
repository = 'othree/html5.vim'

# laravle blade
[[plugins]]
repository = 'xsbeats/vim-blade'

# handlebars tamplete
[[plugins]]
repository = 'nono/vim-handlebars'

# lepture/vim-css css3シンタックス
[[plugins]]
repository = 'hail2u/vim-css3-syntax'

# scss
[[plugins]]
repository = 'cakebaker/scss-syntax.vim'

# php.vim のfork版 (php syntax, 補完)
[[plugins]]
repository = 'StanAngeloff/php.vim'

# coffeescript syntax
[[plugins]]
repository = 'kchmck/vim-coffee-script'

# less syntax
[[plugins]]
repository = 'less.vim'

# handlebars and mustache
[[plugins]]
repository = 'mustache/vim-mustache-handlebars'

# actionscript
[[plugins]]
repository = 'endel/actionscript.vim'

#as3 omni comp
[[plugins]]
repository = 'yuratomo/flex-api-complete'

# sql
[[plugins]]
repository = 'vim-scripts/SQLComplete.vim'

# jsx (react)
[[plugins]]
repository = 'mxw/vim-jsx'

# vim-ruby (ruby syntax, 補完)
[[plugins]]
repository = 'vim-ruby/vim-ruby'

# javascript syntax
[[plugins]]
repository = 'jelera/vim-javascript-syntax'

[[plugins]]
#repository = 'plasticboy/vim-markdown'
repository = 'jtratner/vim-flavored-markdown'

##################################################
# Completion
##################################################

# Completion Framework
[[plugins]]
repository = 'Shougo/neocomplete.vim'

# java Omni補完
[[plugins]]
repository = 'artur-shaik/vim-javacomplete2'


##################################################
# Color Scheme
##################################################

[[plugins]]
repository = 'nanotech/jellybeans.vim'

[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repository = 'vim-scripts/twilight'

[[plugins]]
repository = 'jonathanfilip/vim-lucius'

[[plugins]]
repository = 'jpo/vim-railscasts-theme'

[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'vim-scripts/Wombat'

[[plugins]]
repository = 'tomasr/molokai'

[[plugins]]
repository = 'vim-scripts/rdark'

[[plugins]]
repository = 'jdonaldson/vaxe'

[[plugins]]
repository = 'cocopon/iceberg.vim'

#[[plugins]]
#repository = 'daylerees/colour-schemes', { 'rtp': 'vim/' }

# base16 color
[[plugins]]
repository = 'chriskempson/base16-vim'

[[plugins]]
repository = 'jdkanani/vim-material-theme'

[[plugins]]
repository = 'kristijanhusak/vim-hybrid-material'

