vim.cmd('packadd! nvim.undotree')
vim.cmd('packadd! nvim.difftool')

require("plugins/which-key")
require("plugins/nvim-pack-ui")
require("plugins/mini")

--
require("plugins/bufferline")
-- require("plugins/blink-cmp")
require("plugins/conform")
-- require("plugins/flash")
require("plugins/gitsigns")
require("plugins/helpview")
require("plugins/kakehashi")
require("plugins/lazydev")
require("plugins/lspkind")
require("plugins/lualine")
require("plugins/modes")
require("plugins/neo-tree")
require("plugins/notifier")
require("plugins/nvim-autopairs")
-- require("plugins/nvim-tree")
require("plugins/nvim-lspconfig")
require("plugins/nvim-treesitter")
require("plugins/nvim-web-devicons")
require("plugins/nvim-surround")
require("plugins/quicker")
require("plugins/react-compiler-maker")
require("plugins/smooth-resize")
require("plugins/telescope")
require("plugins/tiny-cmdline")
require("plugins/tiny-code-action")
require("plugins/tiny-inline-diagnostic")
require("plugins/tokyonight")
require("plugins/ts-error-translator")
require("plugins/tsc")
require("plugins/translate")
require("plugins/workspace-diagnostics")
require("plugins/vim-tmux-navigator")
