local PLUGIN_NAME = 'react-compiler-marker'

vim.pack.add({
  { src = 'https://github.com/blazejkustra/react-compiler-marker', name = PLUGIN_NAME },
})

local plugin = vim.pack.get({ PLUGIN_NAME }, { info = false })[1]

if not plugin then
  return
end

local dir = plugin.path

local function setup()
  -- lua/ is generated by the build, so drop the loader cache before requiring
  pcall(vim.loader.reset, dir)

  local ok, rcm = pcall(require, PLUGIN_NAME)

  if not ok then
    vim.notify(PLUGIN_NAME .. ': ' .. tostring(rcm), vim.log.levels.ERROR)
  elseif not rcm._setup_done then
    -- See packages/nvim-client/README.md for the available options
    rcm.setup({})
  end
end

local function build()
  vim.notify(PLUGIN_NAME .. ': building LSP server...')

  vim.system(
    { 'bash', dir .. '/scripts/build-nvim.sh' },
    { cwd = dir, text = true },
    vim.schedule_wrap(function(obj)
      if obj.code == 0 then
        setup()
      else
        vim.notify(PLUGIN_NAME .. ': build failed\n' .. (obj.stderr or ''), vim.log.levels.ERROR)
      end
    end)
  )
end

-- Rebuild after an update since the artifacts are stale
-- (install is covered by the "not built yet" check below)
vim.api.nvim_create_autocmd('PackChanged', {
  callback = function(ev)
    if ev.data.spec.name == PLUGIN_NAME and ev.data.kind == 'update' then
      build()
    end
  end,
})

if vim.uv.fs_stat(dir .. '/server/server.bundle.js') then
  setup()
else
  build()
end
